// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

namespace Januar_2021.Migrations
{
    [DbContext(typeof(PrognozaContext))]
    partial class PrognozaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Models.Grad", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Godina")
                        .HasColumnType("int");

                    b.Property<string>("ImeGrada")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latituda")
                        .HasColumnType("float");

                    b.Property<double>("Longituda")
                        .HasColumnType("float");

                    b.Property<string>("SlikaGrada")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Grad");
                });

            modelBuilder.Entity("Models.Mesec", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("GradID")
                        .HasColumnType("int");

                    b.Property<string>("ImeMeseca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("KolicinaPadavina")
                        .HasColumnType("float");

                    b.Property<double>("ProsecnaTemp")
                        .HasColumnType("float");

                    b.Property<int>("SuncaniDani")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("GradID");

                    b.ToTable("Mesec");
                });

            modelBuilder.Entity("Models.Mesec", b =>
                {
                    b.HasOne("Models.Grad", "Grad")
                        .WithMany("Meseci")
                        .HasForeignKey("GradID");

                    b.Navigation("Grad");
                });

            modelBuilder.Entity("Models.Grad", b =>
                {
                    b.Navigation("Meseci");
                });
#pragma warning restore 612, 618
        }
    }
}
